### PR TITLE
Add array findlast and findlastindex

### LINKED ISSUE #34: Add `Array.prototype.findLast` polyfill?

### PR DESCRIPTION
**Pull request by keithamus**
Closes #34 

This is a big diff because it upgrades typescript, I can pull that out in a separate PR if we deem it worthwhile.

### CODE REVIEW

**Review by iansan5653 — APPROVED** [review]

**Review by dgreif — APPROVED** [review]
Great addition, thanks @keithamus!

**Comment by dgreif** [comment]
Do we need to add these to `src/index.ts`?

**Comment by keithamus** [comment]
yep

**Review by dgreif — APPROVED** [review]

**Comment by keithamus** [comment]
@dgreif i don’t have merge privileges so you’ll need to do the honours please.

**Pull request merged**
