### PR TITLE
Drop redundant polyfills

### PR DESCRIPTION
**Pull request by keithamus**
This drops the following polyfills from the codebase:

 - `AggregateError` - supported in Safari 14+, Firefox ESR+, and [Serenity LadyBird](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Runtime/AggregateError.cpp).
 - `Promise.allSettled` - supported in Safari 13+, Firefox ESR+,  and [Serenity LadyBird](https://github.com/SerenityOS/serenity/blob/4e0b52d00928a6f5b1b6e330e139a1f077d83304/Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp#L150-L190).
 - `Promise.any` - supported in Safari 14+, Firefox ESR+,  and [Serenity LadyBird](https://github.com/SerenityOS/serenity/blob/4e0b52d00928a6f5b1b6e330e139a1f077d83304/Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp#L192-L225).
- `Element.prototype.replaceChildren` - supported in Safari 14+, Firefox ESR+, and [Serenity LadyBird](https://github.com/SerenityOS/serenity/blob/4e0b52d00928a6f5b1b6e330e139a1f077d83304/Userland/Libraries/LibWeb/DOM/ParentNode.cpp#L211-L224)
- `String.prototype.replaceAll` - supported in Safari 13.1+, Firefox ESR+, and [Serenity LadyBird](https://github.com/SerenityOS/serenity/blob/fda619c7c2502d459beb81ef7f07deb26d529178/Userland/Libraries/LibJS/Runtime/StringPrototype.cpp#L865-L10090)

Given [how we think about browsers](https://github.blog/2022-06-10-how-we-think-about-browsers/), these polyfills are not required for the vast majority of our traffic:

#### [AggregateError](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)
| Browser                 | Supported Since | Latest Version | % Supported | % Unsupported |
| :---------------------- | --------------: | -------------: | ----------: | ------------: |
| chrome                  |              85 |            101 |      70.773 |         0.075 |
| edge                    |              85 |            100 |       9.448 |         0.004 |
| firefox                 |              79 |            100 |      12.343 |         0.020 |
| firefox_android         |              79 |            100 |       0.262 |         0.000 |
| ie                      |   Not Supported |             11 |       0.000 |         0.008 |
| opera                   |              71 |             86 |       1.567 |         0.000 |
| safari                  |              14 |           15.4 |       3.979 |         0.021 |
| safari_ios              |              14 |           15.4 |       1.086 |         0.044 |
| samsunginternet_android |            14.0 |           16.0 |       0.089 |         0.000 |
| webview_android         |              85 |            101 |       0.007 |         0.021 |
| **Total:**              |                 |                |  **99.554** |     **0.193** |

#### [Promise.allSettled](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)
| Browser                 | Supported Since | Latest Version | % Supported | % Unsupported |
| :---------------------- | --------------: | -------------: | ----------: | ------------: |
| chrome                  |              76 |            101 |      70.807 |         0.041 |
| edge                    |              79 |            100 |       9.450 |         0.003 |
| firefox                 |              71 |            100 |      12.356 |         0.007 |
| firefox_android         |              79 |            100 |       0.262 |         0.000 |
| ie                      |   Not Supported |             11 |       0.000 |         0.008 |
| opera                   |              63 |             86 |       1.567 |         0.000 |
| safari                  |              13 |           15.4 |       3.990 |         0.010 |
| safari_ios              |              13 |           15.4 |       1.091 |         0.039 |
| samsunginternet_android |            12.0 |           16.0 |       0.089 |         0.000 |
| webview_android         |              76 |            101 |       0.008 |         0.021 |
| **Total:**              |                 |                |   **99.62** |     **0.129** |

#### [Promise.any](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)
| Browser                 | Supported Since | Latest Version | % Supported | % Unsupported |
| :---------------------- | --------------: | -------------: | ----------: | ------------: |
| chrome                  |              85 |            101 |      70.773 |         0.075 |
| edge                    |              85 |            100 |       9.448 |         0.004 |
| firefox                 |              79 |            100 |      12.343 |         0.020 |
| firefox_android         |              79 |            100 |       0.262 |         0.000 |
| ie                      |   Not Supported |             11 |       0.000 |         0.008 |
| opera                   |              71 |             86 |       1.567 |         0.000 |
| safari                  |              14 |           15.4 |       3.979 |         0.021 |
| safari_ios              |              14 |           15.4 |       1.086 |         0.044 |
| samsunginternet_android |            14.0 |           16.0 |       0.089 |         0.000 |
| webview_android         |              85 |            101 |       0.007 |         0.021 |
| **Total:**              |                 |                |  **99.554** |     **0.193** |

#### [Element.prototype.replaceChildren](https://developer.mozilla.org/docs/Web/API/Element/replaceChildren)
| Browser                 | Supported Since | Latest Version | % Supported | % Unsupported |
| :---------------------- | --------------: | -------------: | ----------: | ------------: |
| chrome                  |              86 |            101 |      70.687 |         0.160 |
| edge                    |              86 |            100 |       9.448 |         0.005 |
| firefox                 |              78 |            100 |      12.355 |         0.008 |
| firefox_android         |              79 |            100 |       0.262 |         0.000 |
| ie                      |   Not Supported |             11 |       0.000 |         0.008 |
| opera                   |              72 |             86 |       1.567 |         0.000 |
| safari                  |              14 |           15.4 |       3.979 |         0.021 |
| safari_ios              |              14 |           15.4 |       1.086 |         0.044 |
| samsunginternet_android |            14.0 |           16.0 |       0.089 |         0.000 |
| webview_android         |              86 |            101 |       0.007 |         0.021 |
| **Total:**              |                 |                |   **99.48** |     **0.267** |

#### [String.prototype.replaceAll](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)
| Browser                 | Supported Since | Latest Version | % Supported | % Unsupported |
| :---------------------- | --------------: | -------------: | ----------: | ------------: |
| chrome                  |              85 |            101 |      70.773 |         0.075 |
| edge                    |              85 |            100 |       9.448 |         0.004 |
| firefox                 |              77 |            100 |      12.355 |         0.008 |
| firefox_android         |              79 |            100 |       0.262 |         0.000 |
| ie                      |   Not Supported |             11 |       0.000 |         0.008 |
| opera                   |              71 |             86 |       1.567 |         0.000 |
| safari                  |            13.1 |           15.4 |       3.990 |         0.010 |
| safari_ios              |            13.4 |           15.4 |       1.088 |         0.042 |
| samsunginternet_android |            14.0 |           16.0 |       0.089 |         0.000 |
| webview_android         |              85 |            101 |       0.007 |         0.021 |
| **Total:**              |                 |                |  **99.579** |     **0.168** |

### CODE REVIEW

**Comment by jfuchs** [comment]
@keithamus hi! is this ready for review?

**Comment by keithamus** [comment]
Sure, it can be. This is a BREAKING change. We _could_ wait until September when Safari 17 is likely to be released.

**Comment by dgreif** [comment]
👋 hello from October 😄. Looks like Safari 17 is out, so we should be ready to officially drop Safari 13/14 🔥. @keithamus would you mind fixing up the conflicts on this? Or I can take a look as FR next week if you are busy on other projects

**Comment by keithamus** [comment]
Between passion week this week and ActionMenu work next week I might not get round to it, but I'll try to, unless you beat me to it :wink:

**Review by erinnachen — APPROVED** [review]

**Pull request merged**
